org: quoc2110
app: curd-serveless
service: books

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  environment:
    VERSIONS: ${param:VERSIONS, '1'}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: '*'

functions:
  create:
    handler: src/handler.create
    events:
      - http:
          path: books
          method: post
  update:
    handler: src/handler.update
    events:
      - http:
          path: books/{id}
          method: put
  find:
    handler: src/handler.find
    events:
      - http:
          path: books
          method: get
  findOne:
    handler: src/handler.findOne
    events:
      - http:
          path: books/{id}
          method: get
  deleteOne:
    handler: src/handler.deleteOne
    events:
      - http:
          path: books/{id}
          method: delete

plugins:
  - serverless-plugin-typescript 
  - serverless-offline
  - serverless-dynamodb-local